import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Menu from './Menu'
import { getFolders } from '../../cli/sdk'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Regarding my self',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const folders = await getFolders();
  
  return (
    <html lang="en">
      <body className={`${inter.className} bg-grey-50`}>
        <nav className='flex justify-between items-center space-x-6 p-6 border-t-4 border-t-sky-400 bg-gray-100'>
          <h1 className='font-semibold tracking-tighter text-gray-700' >Content</h1>
        <Menu folders={folders.folders}/>
        </nav>
        {children}</body>
    </html>
  )
}
